# Site settings
title: Kornelius Mainstone
description: AKG's CV
favicon: /assets/img/avatar.JPG
baseurl: https://www.kornelius.is
url: https://www.kornelius.is
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Aðalsteinn Kornelíus Gunnarsson
  title: Green Card Holder
  address: MI, Vandalia, USA
  email: adalsteinn@kornelius.is
  link: https://www.kornelius.is
 # weibo:
  github: brosrass
  linkedin: https://www.linkedin.com/feed/
  twitter: KorneliusM
  gavatar: /resumecard/assets/img/avatar.JPG
 # stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Icelandair
      location: Reykjavík, Iceland
      title: Revenue Management Analyst
      started: 2018
      duration: (2018 - Present)
      description: Make sure that revenue and yield is maximized and Icelandair’s competitive position is maintained on a regional & network basis
                | Optimizing route portfolio of 100M. dollars annually
                | Deliver commercial revenue & budget targets for my assigned portfolio
                | Communication and collaboration with key stakeholders 
    - work2:
      company: Icelandair Cargo
      location: Reykjavík, Iceland
      title: Project Manager
      started: 2015
      duration: (2015 - 2018)
      description: Cross project management
                    | Managed various marketing and business development projects with internal and external stakeholders to make ideas into implementation.
                    | Worked with various departments to work on available financial opportunities
                    | Delivered on the long-term vision and strategy of the company through evaluation and implementation of strategic initiatives, financial management, planning and budgeting.
  educationHistory:
    - education1: 
      organization: Copenhagen Business School
      location: Copenhagen, Denmark
      degree: Masters
      major: MSoSc., Organizational Innovation and Entrepreneurship
      started: 2012
      duration: (2012 - 2016)
      description: With this degree I acquired the necessary skills to start a business, create innovations, manage change and resources, and lead others in the process of turning a new idea into a viable business
                  | Leadership in Creative Organizations & Management and Organization in the Creative Society
    - education2: 
      organization: Ministry of Finance and Economic
      location: Reykjavík, Iceland
      degree: Diploma
      major: Licensed Securities Dealer Investment and Securities
      started: 2017
      duration: (2017 - 2018)
      description: Securities broker
      description2: Law, financial markets and business administration curriculum
    - education3: 
      organization: Grenoble Ecole De Management
      location: Grenoble, France
      degree: MIM., Master in Management
      major: Master in Management
      started: 2013
      duration: (2013 - 2014)
      description: Exchange Program from Copenhagen Business School | CMIRA scholarship | Managing Cultural Diversity
    - education4: 
      organization: University of Reykjavík, Iceland
      location: Reykjavík, Iceland
      degree: Bachelor
      major: Bsc., Business Administration
      started: 2009
      duration: (2009 - 2012)
      description: Bachelor degree
  languages:
    - language1:
      name: Icelandic
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Danish
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: Presentations
      percentage: 100%
    - skill2:
      name: Google "I'm Felling Lucky"
      percentage: 100%
    - skill3:
      name: Coding/Web Development (learning)
      percentage: 20%
    - skill4:
      name: Microsoft Office
      percentage: 100%
    - skill5:
      name: Financial analysis
      percentage: 100%
