# Site settings
title: AKG's CV 
description: AKG's CV
favicon: /assets/img/avatar.JPG
baseurl: https://www.kornelius.is
url: https://www.kornelius.is
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Aðalsteinn Kornelíus Gunnarsson
  title: Kornelius
  address: MI, Vandalia, USA
  email: adalsteinn@kornelius.is
  link: https://www.kornelius.is
 # weibo:
  github: brosrass
  linkedin: https://www.linkedin.com/feed/
 # twitter: ddbullfrog
  gavatar: /resumecard/assets/img/avatar.JPG
 # stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Icelandair
      location: Reykjavík, Iceland
      title: Revenue Management Analyst
      started: 2018
      duration: (2018 - Present)
      description: Make sure that revenue and yield is maximized and Icelandair’s competitive position is maintained on a regional & network basis
                | Optimizing route portfolio of 100M. dollars annually
                | Deliver commercial revenue & budget targets for my assigned portfolio
                | Communication and collaboration with key stakeholders 
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
